[tool.poetry]
name = "jiratools"
version = "2.1.0"
description = "Simple helpers to interface to JIRA from an API or command line."
authors = ["Brad Brown <brad@bradsbrown.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/jolly-good-toolbelt/jiratools/"
documentation = "https://jolly-good-toolbelt.github.io/jiratools/"
repository = "https://github.com/jolly-good-toolbelt/jiratools/"

[tool.poetry.dependencies]
python = "^3.6"
jira = "^2.0"
jgt_common = "^1.0"

[tool.poetry.dev-dependencies]
pre-commit = "^1.17"
sphinx = "^2.0"
sphinx-rtd-theme = "^0.4.3"
ghp-import = "^0.5.5"
tomlkit = "^0.5.3"
sphinx-autodoc-typehints = "^1.6"

[tool.poetry.scripts]
jira-link-issues = "jiratools:jira_link"
jira-make-linked-issue = "jiratools:make_linked"
jira-add-comment = "jiratools:add_comment"
jira-search-issues = "jiratools:search"
jira-update-assignee = "jiratools:reassign"
jira-example-config = "jiratools:example_config_install"
jiratool = "jiratools:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
